name: club_alt
description: "Book Affordable Flights With Ease!"
publish_to: 'none'

version: 1.0.2+5

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  domain:
    path: domain
  data:
    path: data
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  go_router: 13.0.0
  flutter_svg: 2.0.0
  fluttertoast: ^9.0.0
  flutter_screenutil: 5.9.0
  google_fonts: 6.1.0 # For custom fonts
  buttons_tabbar: ^1.3.14
  intl_phone_field: ^3.1.0
  mime: ^1.0.4
  image_picker: ^0.8.5+3
  file_picker: ^8.3.1
  path_provider: ^2.1.5
  webview_flutter: ^4.10.0
  url_launcher: ^6.2.4




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependency_overrides:
  webview_flutter_wkwebview: 3.17.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - env/
    - assets/images/
  fonts:
    - family: Neuropa
      fonts:
        - asset: assets/fonts/neuropa/Neuropa-Medium.otf
          weight: 500
        - asset: assets/fonts/neuropa/Neuropa-Extra-Light.otf
          weight: 200
        - asset: assets/fonts/neuropa/Neuropa-Bold.otf
          weight: 700
        - asset: assets/fonts/neuropa/Neuropa-Light.otf
          weight: 300
        - asset: assets/fonts/neuropa/Neuropa-Heavy.otf
          weight: 900

    - family: Graphik
      fonts:
        - asset: assets/fonts/graphik/GraphikMedium.otf
          weight: 500
        - asset: assets/fonts/graphik/GraphikLight.otf
          weight: 300
        - asset: assets/fonts/graphik/GraphikRegular.otf
          weight: 400
        - asset: assets/fonts/graphik/GraphikBold.otf
          weight: 700
        - asset: assets/fonts/graphik/GraphikExtralight.otf
          weight: 200
        - asset: assets/fonts/graphik/GraphikSemibold.otf
          weight: 600
